version: '3.8'

services:
  bot:
    build: .
    container_name: cyber-nick-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./cyber_nick.db:/app/cyber_nick.db
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge